"""adjustment

Revision ID: 6524e9c7eb59
Revises: 845520977b2c
Create Date: 2021-06-23 22:28:39.027689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6524e9c7eb59'
down_revision = '845520977b2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('about', sa.String(length=255), nullable=True))
    op.alter_column('business', 'location',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_index(op.f('ix_business_location'), 'business', ['location'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_business_location'), table_name='business')
    op.alter_column('business', 'location',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('business', 'about')
    # ### end Alembic commands ###
